name: Roblox XVC Fetch and Release
permissions: write-all

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:
  push:

jobs:
  fetch-and-release:
    runs-on: ubuntu-latest

    env:
      PRODUCT_URL: https://displaycatalog.mp.microsoft.com/v7.0/products?bigIds=BQ1TN1T79V9K&market=US&languages=en-US,neutral&MS-CV=DGU1mcuYo0WMMp+F.1

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download product.json
        run: |
          curl -sSL "$PRODUCT_URL" -o product.json
          cat product.json

      - name: Extract contentId
        id: extract
        run: |
          contentId=$(jq -r '.Products[0].DisplaySkuAvailabilities[0].Sku.Properties.Packages[0].ContentId' product.json)
          echo "contentId=$contentId" >> "$GITHUB_OUTPUT"

      - name: Get latest release contentId
        id: get_latest
        continue-on-error: true
        run: |
          latest_json=$(curl -sSL \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/releases/latest)

          desc=$(echo "$latest_json" | jq -r '.body // ""')
          if echo "$desc" | grep -q 'ContentId:'; then
            latest_cid=$(echo "$desc" | grep -o 'ContentId: .*' | cut -d' ' -f2)
            echo "latest_content_id=$latest_cid" >> "$GITHUB_OUTPUT"
          else
            echo "latest_content_id=none" >> "$GITHUB_OUTPUT"
          fi

      - name: Get download URL from API
        id: apicall
        if: steps.extract.outputs.contentId != steps.get_latest.outputs.latest_content_id
        run: |
          response=$(curl -sSL -X GET "${{ secrets.XBOX_BASEURL }}/Game/GetGamePackage?contentId=${{ steps.extract.outputs.contentId }}&platform=0" \
            -H "User-Agent: ${{ secrets.XBOX_USER_AGENT }}" \
            -H "X-Organization: ${{ secrets.XBOX_ORGANIZATION }}" \
            -H "X-Author: ${{ secrets.XBOX_AUTHOR }}" )

          echo "$response" | jq '.'

          xvc_url=$(echo "$response" | jq -r '.data.url')
          filename=$(basename "$xvc_url")
          echo "xvc_url=$xvc_url" >> "$GITHUB_OUTPUT"
          echo "filename=$filename" >> "$GITHUB_OUTPUT"

      - name: Download .xvc file
        if: steps.extract.outputs.contentId != steps.get_latest.outputs.latest_content_id
        run: |
          curl -sSL "${{ steps.apicall.outputs.xvc_url }}" -o "${{ steps.apicall.outputs.filename }}.xvc"

      - name: Upload release using ncipollo/release-action
        if: steps.extract.outputs.contentId != steps.get_latest.outputs.latest_content_id
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.apicall.outputs.filename }}
          name: ${{ steps.apicall.outputs.filename }}
          body: |
            ${{ steps.apicall.outputs.filename }}

            ContentId: ${{ steps.extract.outputs.contentId }}
          artifacts: |
            product.json
            ${{ steps.apicall.outputs.filename }}.xvc
